# Generated by Django 6.0.5 on 2026-05-21 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desk', '0004_userprofile_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='privacy',
            field=models.CharField(choices=[('PUBLIC', '🌍 Public - Everyone can see'), ('PRIVATE', '🔒 Private - Only ministry admin can see')], default='PUBLIC', max_length=10),
        ),
    ]
