# Generated by Django 6.0.5 on 2026-05-21 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desk', '0005_report_latitude_report_longitude_report_privacy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='report_type',
        ),
        migrations.AlterField(
            model_name='reaction',
            name='reaction_type',
            field=models.CharField(choices=[('ACKNOWLEDGED', '✅ Acknowledged'), ('ESCALATED', '⚠️ Escalated'), ('RESOLVED', '✔️ Resolved')], default='ACKNOWLEDGED', max_length=15),
        ),
    ]
