# Generated by Django 6.0.5 on 2026-05-21 19:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desk', '0006_remove_report_report_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='managed_ministry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admins', to='desk.ministry'),
        ),
    ]
