# Generated by Django 6.0.5 on 2026-06-03 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desk', '0009_category_report_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='region_of_origin',
            field=models.CharField(blank=True, choices=[('CENTRAL', 'Central'), ('EASTERN', 'Eastern'), ('NORTHERN', 'Northern'), ('WESTERN', 'Western'), ('KAMPALA', 'Kampala'), ('OTHER', 'Other')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='region_of_residence',
            field=models.CharField(blank=True, choices=[('CENTRAL', 'Central'), ('EASTERN', 'Eastern'), ('NORTHERN', 'Northern'), ('WESTERN', 'Western'), ('KAMPALA', 'Kampala'), ('OTHER', 'Other')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='sex',
            field=models.CharField(blank=True, choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('OTHER', 'Other'), ('PREFER_NOT_TO_SAY', 'Prefer not to say')], max_length=20, null=True),
        ),
    ]
