# Generated by Django 6.0.5 on 2026-06-04 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desk', '0010_userprofile_date_of_birth_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={},
        ),
        migrations.AddField(
            model_name='report',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
